### ISSUE TITLE
No way to connect over TLS/SSL

### ISSUE THREAD

**Issue by stephenreay** [gabfl/dbschema#12]
It's pretty much essential to use TLS/SSL for a remote connection, but there's no way to do that currently.

For PyMYSQL we'd need a way to set the CA cert at the very least. 

I'm not sure what's needed to make this work for Postgres, I don't use it regularly.

**Comment by gabfl** [comment]
Merged and built with version 1.2.5

**Comment by gabfl** [comment]
I will try to add the same feature for Postgres later on

**Comment by gabfl** [comment]
Hi @stephenreay, I am not sure if you cared about the feature or not but I just pushed a new version to support SSL connections with PostgreSQL to complement your PR
