### ISSUE TITLE
Migrations are not run in order

### ISSUE THREAD

**Issue by stephenreay** [gabfl/dbschema#14]
dbschema relies on python's `glob.glob` function, which explicitly states (emphasis mine):

> The glob module finds all the pathnames matching a specified pattern according to the rules used by the Unix shell, **although results are returned in arbitrary order**.

I expect to file a PR with a quick-and-dirty solution for this today.

**Comment by gabfl** [comment]
Thank you for the PR @stephenreay

**Comment by gabfl** [comment]
new version has been pushed to pypi: https://pypi.org/project/dbschema/#description
