### ISSUE TITLE
dbschema doesn't connect to specified `host`

### ISSUE THREAD

**Issue by stephenreay** [gabfl/dbschema#3]
Setting a `host` parameter in the config file is ignored: it always attempts to connect to `localhost`.

This appears to be because of: https://github.com/gabfl/dbschema/blob/c57865dea3c0a4d2de107b877784b0ba28fb0ae2/src/schema_change.py#L280

Presumably this should read `.get('host', 'localhost')` instead?

**Comment by stephenreay** [comment]
Any update? I've sent a PR that should fix this, but no response yet?

**Comment by stephenreay** [comment]
Ping?

**Comment by gabfl** [comment]
HI @stephenreay, I apologize, my notifications were disabled. Let me look into this and get back to you

**Comment by stephenreay** [comment]
Hi @gabfl,

No worries. Any idea when you'll get an updated version pushed to pypi?

Thanks!

**Comment by gabfl** [comment]
I merged both of your branches. I had my own fix for your issue #5 but yours was better so I rolled back my changes and used yours instead.

Both of your PRs are part of the release 1.2.1 that was pushed a few minutes ago: https://pypi.org/project/dbschema/

Please feel free to contribute again. I made sure to reactivate notifications and will get back to you quickly next time!

**Comment by stephenreay** [comment]
Thanks for the update.

If I find any other issues I'll be sure to file bugs and PRs too, if I can (Python isn't my day to day language)
